# Generated by Django 4.2 on 2023-04-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('tag', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
