# Generated by Django 4.2 on 2023-05-08 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiProjeto3', '0002_customdate_customdateitem_day_publicholiday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feriado',
            name='custom_dates',
        ),
        migrations.RemoveField(
            model_name='feriado',
            name='days',
        ),
        migrations.RemoveField(
            model_name='feriado',
            name='public_holidays',
        ),
        migrations.RemoveField(
            model_name='feriado',
            name='public_holidaysDate',
        ),
        migrations.RemoveField(
            model_name='feriado',
            name='weekend_days',
        ),
        migrations.RemoveField(
            model_name='feriado',
            name='working_days',
        ),
        migrations.DeleteModel(
            name='PublicHolidayDate',
        ),
        migrations.DeleteModel(
            name='CustomDate',
        ),
        migrations.DeleteModel(
            name='CustomDateItem',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Feriado',
        ),
        migrations.DeleteModel(
            name='PublicHoliday',
        ),
        migrations.DeleteModel(
            name='WeekendDay',
        ),
        migrations.DeleteModel(
            name='WorkingDay',
        ),
    ]
