# Generated by Django 4.2 on 2023-05-08 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiProjeto3', '0004_rotina'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rotina',
        ),
    ]
