# Generated by Django 4.2 on 2023-05-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiProjeto3', '0005_delete_rotina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=16)),
                ('day', models.TextField()),
                ('month', models.TextField()),
                ('year', models.TextField()),
            ],
        ),
    ]
