# Generated by Django 4.2.1 on 2023-05-09 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiProjeto3', '0006_rotina'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rotina',
        ),
    ]
