# Generated by Django 4.2.1 on 2023-05-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiProjeto3', '0007_delete_rotina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=16)),
                ('day', models.TextField()),
                ('month', models.TextField()),
                ('year', models.TextField()),
                ('feito', models.BooleanField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
